version: '3.8'
services:
  # maven:
  #   build:
  #     context: .
  #     dockerfile: maven.Dockerfile
  #   volumes:
  #     - ./apiproductos:/app
  #   command: mvn clean package
  #   networks:
  #     - my-network

  # wildfly:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./apiproductos/target/apiproductos-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/apiproductos-1.0-SNAPSHOT.war
  #   depends_on:
  #     - mysql
  #   networks:
  #     - my-network

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: productos_db
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
